export type RecordItem={id:string;group:'Gabinete'|'Entidad'|'Territorio';title:string;holder:string;subtitle:string;mission:string;norm:string;source:string;verified:boolean;updated:string;parent?:string};

export const cabinet:RecordItem[]=[
['vicepresidencia','Vicepresidencia','José Manuel Restrepo'],['interior','Interior','Rodrigo Lara Restrepo'],['relaciones','Relaciones Exteriores','Omar Bula Escobar'],['hacienda','Hacienda y Crédito Público','Miguel Gómez Martínez'],['justicia','Justicia y del Derecho','Iván Alfonso Cancino'],['defensa','Defensa Nacional','Jorge Eduardo Mora'],['agricultura','Agricultura y Desarrollo Rural','Indalecio Dangond'],['salud','Salud y Protección Social','Ana María Vesga'],['trabajo','Trabajo','Natalia López Fuentes'],['minas','Minas y Energía','María Nohemí Arboleda'],['comercio','Comercio, Industria y Turismo','Mauricio Gómez Amín'],['educacion','Educación Nacional','Viviane Morales'],['ambiente','Ambiente y Desarrollo Sostenible','Fabio Alberto Arjona'],['vivienda','Vivienda, Ciudad y Territorio','Jaime Andrés Beltrán'],['tic','Tecnologías de la Información y las Comunicaciones','Alexandra Falla'],['transporte','Transporte','Elsa Margarita Noguera'],['cultura','Culturas, las Artes y los Saberes','Paola Andrea Holguín'],['deporte','Deporte','Juliana Gutiérrez']
].map(([id,title,holder])=>({id,group:'Gabinete',title:`Ministerio de ${title}`,holder,subtitle:id==='vicepresidencia'?'Vicepresidente de la República':'Ministro/a del despacho',mission:id==='vicepresidencia'?'Reemplaza al Presidente en sus faltas y cumple los encargos que este le confíe.':`Formula y dirige la política nacional del sector ${title}.`,norm:id==='vicepresidencia'?'Constitución Política · art. 202':'Ley 489 de 1998 · arts. 58 y 59',source:'Presidencia de la República · Gabinete 2026',verified:true,updated:'2026-08-24'} as RecordItem));

const sectorEntities:Record<string,string[]>={
interior:['Unidad Nacional de Protección · UNP','Migración Colombia','Dirección Nacional de Bomberos'],relaciones:['Fondo Rotatorio de Relaciones Exteriores'],hacienda:['DIAN','Superintendencia Financiera','UGPP','UIAF','Fondo Adaptación'],justicia:['INPEC','USPEC','Agencia Nacional de Defensa Jurídica del Estado','Superintendencia de Notariado y Registro'],defensa:['Hospital Militar Central','Defensa Civil Colombiana','Caja de Retiro de las Fuerzas Militares'],agricultura:['ICA','Agencia Nacional de Tierras · ANT','Agencia de Desarrollo Rural · ADR','AUNAP'],salud:['Instituto Nacional de Salud · INS','INVIMA','Superintendencia Nacional de Salud','ADRES'],trabajo:['SENA','Unidad del Servicio Público de Empleo','Superintendencia del Subsidio Familiar'],minas:['Agencia Nacional de Minería · ANM','Agencia Nacional de Hidrocarburos · ANH','UPME','Servicio Geológico Colombiano'],comercio:['Superintendencia de Industria y Comercio','Superintendencia de Sociedades','ProColombia','Instituto Nacional de Metrología'],educacion:['ICETEX','ICFES'],ambiente:['ANLA','Instituto Humboldt','IDEAM'],vivienda:['Fonvivienda','Superintendencia de Servicios Públicos Domiciliarios'],tic:['Agencia Nacional del Espectro','Fondo Único TIC','RTVC'],transporte:['ANI','Aeronáutica Civil','Agencia Nacional de Seguridad Vial','Superintendencia de Transporte'],cultura:['Instituto Colombiano de Antropología e Historia','Archivo General de la Nación'],deporte:['Escuela Nacional del Deporte']};
export const entities:RecordItem[]=Object.entries(sectorEntities).flatMap(([parent,names])=>names.map((title,i)=>({id:`${parent}-${i}`,group:'Entidad',title,holder:'Dirección de entidad',subtitle:'Entidad adscrita, vinculada o del sector',mission:`Ejecuta funciones especializadas bajo la orientación del sector ${cabinet.find(c=>c.id===parent)?.title.replace('Ministerio de ','')||parent}.`,norm:'Ley 489 de 1998 · arts. 38 y 68',source:'Función Pública · Manual de Estructura del Estado',verified:true,updated:'2026-08-24',parent})));

const governors=[['Amazonas','Óscar Enrique Sánchez Guerrero'],['Antioquia','Andrés Julián Rendón Cardona'],['Arauca','Renson Jesús Martínez Prada'],['Atlántico','Eduardo Verano de la Rosa'],['Bolívar','Yamil Hernando Arana Padauí'],['Boyacá','Carlos Andrés Amaya Rodríguez'],['Caldas','Henry Gutiérrez Ángel'],['Caquetá','Luis Francisco Ruiz Aguilar'],['Casanare','César Ortiz Zorro'],['Cauca','Octavio Guzmán Gutiérrez'],['Cesar','Elvia Milena Sanjuán Dávila'],['Chocó','Nubia Carolina Córdoba Curi'],['Córdoba','Erasmo Elías Zuleta Bechara'],['Cundinamarca','Jorge Emilio Rey Ángel'],['Guainía','Arnulfo Rivera Naranjo'],['Guaviare','Yeison Rojas'],['Huila','Rodrigo Villalba Mosquera'],['La Guajira','Jairo Aguilar Deluque'],['Magdalena','Rafael Alejandro Martínez'],['Meta','Rafaela Cortés Zambrano'],['Nariño','Luis Alfonso Escobar Jaramillo'],['Norte de Santander','William Villamizar Laguado'],['Putumayo','Carlos Andrés Marroquín Luna'],['Quindío','Juan Miguel Galvis Bedoya'],['Risaralda','Juan Diego Patiño Ochoa'],['San Andrés y Providencia','Nicolás Gallardo Vásquez'],['Santander','Juvenal Díaz Mateus'],['Sucre','Lucy Inés García Montes'],['Tolima','Adriana Magali Matiz Vargas'],['Valle del Cauca','Dilian Francisca Toro Torres'],['Vaupés','Luis Alfredo Gutiérrez García'],['Vichada','Hecson Alexys Benito Castro']];
export const territories:RecordItem[]=governors.map(([title,holder],i)=>({id:`dep-${i}`,group:'Territorio',title,holder,subtitle:'Gobernador/a · periodo 2024–2027',mission:'Dirige la administración seccional y representa legalmente al departamento.',norm:'Constitución Política · arts. 303 y 305',source:'Resultados territoriales 2023 y sitio de la gobernación',verified:i<8,updated:i<8?'2026-08-24':'2026-08-18'}));

export const capitalMayors:RecordItem[]=[['Bogotá D. C.','Carlos Fernando Galán'],['Medellín','Federico Gutiérrez'],['Cali','Alejandro Eder'],['Barranquilla','Alejandro Char'],['Cartagena','Dumek Turbay'],['Bucaramanga','Cristian Portilla'],['Manizales','Jorge Eduardo Rojas'],['Montería','Hugo Kerguelén'],['Quibdó','Rafael Bolaños']].map(([title,holder],i)=>({id:`alc-${i}`,group:'Territorio',title,holder,subtitle:'Alcalde de ciudad capital · 2024–2027',mission:'Dirige la administración local y representa legalmente al municipio o distrito.',norm:'Constitución Política · arts. 314 y 315',source:'Registraduría / sitio de la alcaldía',verified:i<5,updated:'2026-08-24'}));
export const allRecords=[...cabinet,...entities,...territories,...capitalMayors];
