export type RecordItem={id:string;group:'Gabinete'|'Entidad'|'Territorio';title:string;holder:string;subtitle:string;mission:string;norm:string;source:string;sourceUrl?:string;verified:boolean;updated:string;parent?:string;code?:'MIN'|'VP'|'ENT'|'DER'|'MUN'|'DC'};

export const cabinet:RecordItem[]=[
['vicepresidencia','Vicepresidencia','José Manuel Restrepo'],['interior','Interior','Rodrigo Lara Restrepo'],['relaciones','Relaciones Exteriores','Omar Bula Escobar'],['hacienda','Hacienda y Crédito Público','Miguel Gómez Martínez'],['justicia','Justicia y del Derecho','Iván Alfonso Cancino'],['defensa','Defensa Nacional','Jorge Eduardo Mora'],['agricultura','Agricultura y Desarrollo Rural','Indalecio Dangond'],['salud','Salud y Protección Social','Ana María Vesga'],['trabajo','Trabajo','Natalia López Fuentes'],['minas','Minas y Energía','María Nohemí Arboleda'],['comercio','Comercio, Industria y Turismo','Mauricio Gómez Amín'],['educacion','Educación Nacional','Viviane Morales'],['ambiente','Ambiente y Desarrollo Sostenible','Fabio Alberto Arjona'],['vivienda','Vivienda, Ciudad y Territorio','Jaime Andrés Beltrán'],['tic','Tecnologías de la Información y las Comunicaciones','Alexandra Falla'],['transporte','Transporte','Elsa Margarita Noguera'],['cultura','Culturas, las Artes y los Saberes','Paola Andrea Holguín'],['deporte','Deporte','Juliana Gutiérrez']
].map(([id,title,holder])=>({id,group:'Gabinete',title:id==='vicepresidencia'?'Vicepresidencia':`Ministerio de ${title}`,holder,subtitle:id==='vicepresidencia'?'Vicepresidente de la República · no es un ministerio':'Ministro/a del despacho',mission:id==='vicepresidencia'?'Reemplaza al Presidente en sus faltas y cumple los encargos que este le confíe.':`Formula y dirige la política nacional del sector ${title}.`,norm:id==='vicepresidencia'?'Constitución Política · art. 202':'Ley 489 de 1998 · arts. 58 y 59',source:'Presidencia de la República — Gabinete Ministerial Presidencial 2026',sourceUrl:'https://www.presidencia.gov.co/contenidoVinculado/pre26-gabinete-mesa.html',verified:true,updated:'2026-08-24',code:id==='vicepresidencia'?'VP':'MIN'} as RecordItem));

const sectorEntities:Record<string,string[]>={
interior:['Unidad Nacional de Protección · UNP','Migración Colombia','Dirección Nacional de Bomberos'],relaciones:['Fondo Rotatorio de Relaciones Exteriores'],hacienda:['DIAN','Superintendencia Financiera','UGPP','UIAF','Fondo Adaptación','Sociedad de Activos Especiales · SAE'],justicia:['INPEC','USPEC','Agencia Nacional de Defensa Jurídica del Estado','Superintendencia de Notariado y Registro'],defensa:['Hospital Militar Central','Defensa Civil Colombiana','Caja de Retiro de las Fuerzas Militares','Caja Promotora de Vivienda Militar y de Policía · Caja Honor'],agricultura:['ICA','Agencia Nacional de Tierras · ANT','Agencia de Desarrollo Rural · ADR','AUNAP'],salud:['Instituto Nacional de Salud · INS','INVIMA','Superintendencia Nacional de Salud','ADRES'],trabajo:['SENA','Unidad del Servicio Público de Empleo','Superintendencia del Subsidio Familiar'],minas:['Agencia Nacional de Minería · ANM','Agencia Nacional de Hidrocarburos · ANH','UPME','Servicio Geológico Colombiano'],comercio:['Superintendencia de Industria y Comercio','Superintendencia de Sociedades','ProColombia','Instituto Nacional de Metrología'],educacion:['ICETEX','ICFES'],ambiente:['ANLA','Instituto Humboldt','IDEAM'],vivienda:['Fonvivienda','Superintendencia de Servicios Públicos Domiciliarios'],tic:['Agencia Nacional del Espectro','Fondo Único TIC','RTVC'],transporte:['ANI','Aeronáutica Civil','Agencia Nacional de Seguridad Vial','Superintendencia de Transporte'],cultura:['Instituto Colombiano de Antropología e Historia','Archivo General de la Nación'],deporte:['Escuela Nacional del Deporte']};

const decreeIndex='https://dapre.presidencia.gov.co/normativa/decretos-2026/decretos-agosto-2026';
const stateManual='https://www.funcionpublica.gov.co/gestor-normativo/manual-estructura-del-estado/rama-ejecutiva-orden-nacional';
const linkedEntities=new Set([
  'Sociedad de Activos Especiales · SAE','ICETEX','ProColombia','Instituto Humboldt','RTVC','Escuela Nacional del Deporte'
]);
const currentAppointments:Record<string,Partial<RecordItem>>={
  'Unidad Nacional de Protección · UNP':{holder:'Didier Fabián Blanco Rodríguez',subtitle:'Entidad adscrita',norm:'Decreto 1228 del 18 de agosto de 2026',source:'Presidencia de la República · Decreto 1228 de 2026',sourceUrl:decreeIndex,updated:'2026-08-24'},
  'DIAN':{holder:'Andrés Felipe Velásquez Reyes',subtitle:'Entidad adscrita',norm:'Decreto 1184 del 11 de agosto de 2026',source:'Presidencia de la República · Decreto 1184 de 2026',sourceUrl:decreeIndex,updated:'2026-08-24'},
  'ICETEX':{holder:'Richard Alexander Caicedo Rico',subtitle:'Entidad vinculada',norm:'Decreto 1227 del 18 de agosto de 2026',source:'Presidencia de la República e ICETEX',sourceUrl:'https://web.icetex.gov.co/prensa/comunicados',updated:'2026-08-24'},
  'INPEC':{holder:'Daniel Fernando Gutiérrez Rojas',subtitle:'Entidad adscrita',norm:'Decreto 1264 del 20 de agosto de 2026',source:'Presidencia de la República · Decreto 1264 de 2026',sourceUrl:decreeIndex,updated:'2026-08-24'},
  'USPEC':{holder:'Isadora Fernández Posada',subtitle:'Entidad adscrita',norm:'Decreto 1270 del 20 de agosto de 2026',source:'Presidencia de la República · Decreto 1270 de 2026',sourceUrl:decreeIndex,updated:'2026-08-24'},
  'Caja Promotora de Vivienda Militar y de Policía · Caja Honor':{holder:'Pedro Villaquirán Ramos',subtitle:'Entidad adscrita',norm:'Decreto 1269 del 20 de agosto de 2026',source:'Presidencia de la República · Decreto 1269 de 2026',sourceUrl:decreeIndex,updated:'2026-08-24'},
  'Sociedad de Activos Especiales · SAE':{holder:'Diana Patricia Bravo Vélez',subtitle:'Entidad vinculada',norm:'Decreto 1255 del 19 de agosto de 2026',source:'Presidencia de la República · Decreto 1255 de 2026',sourceUrl:decreeIndex,updated:'2026-08-24'}
};
export const entities:RecordItem[]=Object.entries(sectorEntities).flatMap(([parent,names])=>names.map((title,i)=>({id:`${parent}-${i}`,group:'Entidad',title,holder:'Dirección de entidad',subtitle:linkedEntities.has(title)?'Entidad vinculada':'Entidad adscrita',mission:`Ejecuta funciones especializadas bajo la orientación del sector ${cabinet.find(c=>c.id===parent)?.title.replace('Ministerio de ','')||parent}.`,norm:'Ley 489 de 1998 · arts. 38 y 68',source:'Función Pública — Manual de Estructura del Estado Colombiano',sourceUrl:stateManual,verified:true,updated:'2026-08-24',parent,code:'ENT',...currentAppointments[title]} as RecordItem)));

const governors=[['Amazonas','Óscar Enrique Sánchez Guerrero'],['Antioquia','Andrés Julián Rendón Cardona'],['Arauca','Renson Jesús Martínez Prada'],['Atlántico','Eduardo Verano de la Rosa'],['Bolívar','Yamil Hernando Arana Padauí'],['Boyacá','Carlos Andrés Amaya Rodríguez'],['Caldas','Henry Gutiérrez Ángel'],['Caquetá','Luis Francisco Ruiz Aguilar'],['Casanare','César Ortiz Zorro'],['Cauca','Octavio Guzmán Gutiérrez'],['Cesar','Elvia Milena Sanjuán Dávila'],['Chocó','Nubia Carolina Córdoba Curi'],['Córdoba','Erasmo Elías Zuleta Bechara'],['Cundinamarca','Jorge Emilio Rey Ángel'],['Guainía','Arnulfo Rivera Naranjo'],['Guaviare','Yeison Rojas'],['Huila','Rodrigo Villalba Mosquera'],['La Guajira','Jairo Aguilar Deluque'],['Magdalena','Rafael Alejandro Martínez'],['Meta','Rafaela Cortés Zambrano'],['Nariño','Luis Alfonso Escobar Jaramillo'],['Norte de Santander','William Villamizar Laguado'],['Putumayo','Carlos Andrés Marroquín Luna'],['Quindío','Juan Miguel Galvis Bedoya'],['Risaralda','Juan Diego Patiño Ochoa'],['San Andrés y Providencia','Nicolás Gallardo Vásquez'],['Santander','Juvenal Díaz Mateus'],['Sucre','Lucy Inés García Montes'],['Tolima','Adriana Magali Matiz Vargas'],['Valle del Cauca','Dilian Francisca Toro Torres'],['Vaupés','Luis Alfredo Gutiérrez García'],['Vichada','Hecson Alexys Benito Castro']];
export const territories:RecordItem[]=governors.map(([title,holder],i)=>({id:`dep-${i}`,group:'Territorio',title,holder,subtitle:'Departamento · Gobernador/a · periodo 2024–2027',mission:'Dirige la administración seccional y representa legalmente al departamento.',norm:'Constitución Política · arts. 303 y 305',source:'Registraduría Nacional y sitio oficial de la gobernación',verified:i<8,updated:i<8?'2026-08-24':'2026-08-18',code:'DER'}));

const districtCapitals=new Set(['Bogotá D. C.','Medellín','Cali','Barranquilla','Cartagena']);
export const capitalMayors:RecordItem[]=[['Bogotá D. C.','Carlos Fernando Galán'],['Medellín','Federico Gutiérrez'],['Cali','Alejandro Eder'],['Barranquilla','Alejandro Char'],['Cartagena','Dumek Turbay'],['Bucaramanga','Cristian Fernando Portilla Pérez'],['Manizales','Jorge Eduardo Rojas'],['Montería','Hugo Kerguelén'],['Quibdó','Rafael Bolaños']].map(([title,holder],i)=>({id:`alc-${i}`,group:'Territorio',title,holder,subtitle:title==='Bucaramanga'?'Municipio · elegido en elección extraordinaria del 14 dic 2025':districtCapitals.has(title)?'Distrito · Alcalde · periodo 2024–2027':'Municipio · Alcalde · periodo 2024–2027',mission:'Dirige la administración local y representa legalmente al municipio o distrito.',norm:'Constitución Política · arts. 314 y 315',source:title==='Bucaramanga'?'Alcaldía de Bucaramanga — Registraduría entregó credencial al alcalde Cristian Portilla':'Registraduría Nacional y sitio oficial de la alcaldía',sourceUrl:title==='Bucaramanga'?'https://www.bucaramanga.gov.co/noticias/registraduria-entrego-credencial-al-alcalde-cristian-portilla/':undefined,verified:title==='Bucaramanga'||i<5,updated:'2026-08-24',code:districtCapitals.has(title)?'DC':'MUN'}));
export const allRecords=[...cabinet,...entities,...territories,...capitalMayors];

