'use client';
import {useEffect,useMemo,useState} from 'react';
import {allRecords,cabinet,entities,territories,capitalMayors,RecordItem} from './data';
type View='Inicio'|'Gabinete'|'Entidades'|'Territorio'|'Agenda legislativa'|'Editorial';
type Draft={id:string;holder:string;source:string;note:string;date:string};
const bills=[
 {id:'pgn-2027',number:'PL 152/2026 Cámara',title:'Presupuesto General de la Nación 2027',summary:'Fija los ingresos, gastos de funcionamiento, inversión y servicio de la deuda para la vigencia 2027.',status:'Devuelto para ajuste',date:'11 ago 2026',sector:'Hacienda',kind:'Iniciativa gubernamental',source:'https://www.camara.gov.co/presupuesto-general-de-la-nacion-2027/',note:'La ficha oficial registra el número 152/2026C. Comunicaciones posteriores de la Cámara mencionan una numeración distinta; se conserva la ficha legislativa como referencia principal.'},
 {id:'agraria',number:'PL 031/2026 Cámara',title:'Competencias de la Jurisdicción Agraria y Rural',summary:'Define competencias, procedimiento especial y mecanismos para el acceso efectivo a la justicia agraria y rural.',status:'Radicado',date:'21 jul 2026',sector:'Justicia · Agricultura',kind:'Iniciativa congresional',source:'https://www.camara.gov.co/jurisdiccion-agraria-y-rural/',note:'Nueva radicación para la legislatura 2026–2027. No se presenta como proyecto del Gobierno.'},
 {id:'salud',number:'Proyecto de reforma a la salud',title:'Transformación del sistema de salud',summary:'Propuesta gubernamental debatida durante la legislatura 2025–2026 para modificar la organización del sistema de salud.',status:'Archivado',date:'30 jun 2026',sector:'Salud',kind:'Iniciativa gubernamental cerrada',source:'https://www.senado.gov.co/index.php/el-senado/noticias/7444-la-reforma-a-la-salud-uno-de-los-proyectos-mas-debatidos-en-la-comision-septima-en-este-periodo-legislativo',note:'Se incluye como cambio legislativo cerrado: no está en trámite.'},
 {id:'internet',number:'Internet Solidario',title:'Internet asequible para hogares vulnerables',summary:'Propone convertir el internet fijo en servicio público domiciliario y crear un esquema de subsidio para hogares vulnerables.',status:'Vigencia por confirmar',date:'20 ago 2025',sector:'TIC',kind:'Iniciativa gubernamental',source:'https://www.senado.gov.co/index.php/component/content/article/13-senadores/6773-ministerio-tic-radica-proyecto-de-ley-para-garantizar-internet-asequible-a-los-hogares-mas-vulnerables?Itemid=101',note:'La fuente oficial confirma la radicación; la mesa editorial debe verificar su estado en la legislatura 2026–2027.'}
];
export default function GobiernoApp(){
 const[view,setView]=useState<View>('Inicio');const[query,setQuery]=useState('');const[selected,setSelected]=useState<RecordItem>(cabinet[1]);const[sector,setSector]=useState('todos');const[drafts,setDrafts]=useState<Draft[]>([]);const[editing,setEditing]=useState<RecordItem|null>(null);
 useEffect(()=>{try{setDrafts(JSON.parse(localStorage.getItem('gobierno-claro-drafts')||'[]'))}catch{}},[]);
 const saveDraft=(d:Draft)=>{const next=[d,...drafts.filter(x=>x.id!==d.id)];setDrafts(next);localStorage.setItem('gobierno-claro-drafts',JSON.stringify(next));setEditing(null)};
 const exportDrafts=()=>{const blob=new Blob([JSON.stringify({exportedAt:new Date().toISOString(),drafts},null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='gobierno-en-claro-cambios.json';a.click();URL.revokeObjectURL(a.href)};
 const list=useMemo(()=>{const base=view==='Gabinete'?cabinet:view==='Entidades'?entities:[...territories,...capitalMayors];return base.filter(r=>(sector==='todos'||r.parent===sector)&&`${r.title} ${r.holder}`.toLowerCase().includes(query.toLowerCase()))},[view,query,sector]);
 return <main className="v2"><Header view={view} go={setView} query={query} setQuery={setQuery} drafts={drafts.length}/>
 {view==='Inicio'&&<Home go={setView}/>} {view==='Agenda legislativa'&&<Agenda/>} {view==='Editorial'&&<Editorial drafts={drafts} edit={setEditing} exportDrafts={exportDrafts}/>} {(view==='Gabinete'||view==='Entidades'||view==='Territorio')&&<Directory view={view} list={list} selected={selected} select={setSelected} sector={sector} setSector={setSector} edit={setEditing}/>} {editing&&<EditModal item={editing} close={()=>setEditing(null)} save={saveDraft}/>}<footer><span>Gobierno en claro · Prototipo ciudadano v0.3</span><span>Fuentes oficiales prevalecen · corte 24 ago 2026</span></footer></main>
}
function Header({view,go,query,setQuery,drafts}:{view:View;go:(v:View)=>void;query:string;setQuery:(v:string)=>void;drafts:number}){return <header className="topbar"><button className="brand" onClick={()=>go('Inicio')}><span className="mark">CO</span><span>Gobierno<br/><b>en claro</b></span></button><nav>{(['Inicio','Gabinete','Entidades','Territorio','Agenda legislativa','Editorial'] as View[]).map(v=><button key={v} className={view===v?'active':''} onClick={()=>go(v)}>{v}{v==='Editorial'&&drafts>0?<i>{drafts}</i>:null}</button>)}</nav><label className="search">⌕ <input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar persona o entidad…"/></label><span className="updated">Corte editorial<br/><b>24 ago 2026</b></span></header>}
function Home({go}:{go:(v:View)=>void}){return <><section className="homehero"><div><p className="eyebrow">DIRECTORIO + SEGUIMIENTO LEGISLATIVO</p><h1>El Estado,<br/><em>con nombres propios.</em></h1><p>Explora quién decide, quién ejecuta y qué propuestas legislativas están cambiando la agenda pública.</p></div><div className="pulse"><span>100+</span><p>registros institucionales<br/>con trazabilidad</p><i>Fuentes oficiales</i></div></section><section className="portals five"><Portal n="01" title="Gabinete completo" copy="18 carteras + Vicepresidencia" go={()=>go('Gabinete')}/><Portal n="02" title="Entidades adscritas" copy="Agencias, institutos y superintendencias" go={()=>go('Entidades')}/><Portal n="03" title="Gobierno territorial" copy="32 gobernaciones + capitales" go={()=>go('Territorio')}/><Portal n="04" title="Agenda legislativa" copy="Proyectos, estado y fuente oficial" go={()=>go('Agenda legislativa')} agenda/><Portal n="05" title="Mesa editorial" copy="Documenta y exporta correcciones" go={()=>go('Editorial')}/></section></>}
function Portal({n,title,copy,go,agenda}:{n:string;title:string;copy:string;go:()=>void;agenda?:boolean}){return <button className={agenda?'agendaCard':''} onClick={go}><span>{n}</span><p className="eyebrow">{agenda?'NUEVA SECCIÓN':'EXPLORAR'}</p><h2>{title}</h2><p>{copy}</p><b>Abrir →</b></button>}
function Directory({view,list,selected,select,sector,setSector,edit}:{view:View;list:RecordItem[];selected:RecordItem;select:(r:RecordItem)=>void;sector:string;setSector:(v:string)=>void;edit:(r:RecordItem)=>void}){return <section className="directory"><aside className="dirintro"><p className="eyebrow">DIRECTORIO VERIFICABLE</p><h1>{view}</h1><p>Responsables, competencia central, norma fuente y fecha de revisión.</p><div className="metric"><b>{list.length}</b><span>registros visibles</span></div>{view==='Entidades'&&<label className="sectorfilter">SECTOR<select value={sector} onChange={e=>setSector(e.target.value)}><option value="todos">Todos</option>{cabinet.filter(c=>entities.some(e=>e.parent===c.id)).map(c=><option value={c.id} key={c.id}>{c.title.replace('Ministerio de ','')}</option>)}</select></label>}</aside><div className="recordlist"><div className="listhead"><span>{list.length} resultados</span><span><i className="okdot"/> Verificado <i className="pendingdot"/> Por confirmar</span></div>{list.map(r=><button className={`record ${selected.id===r.id?'active':''}`} key={r.id} onClick={()=>select(r)}><span className="recordtype">{r.group==='Gabinete'?'MIN':r.group==='Entidad'?'ENT':'TER'}</span><div><h3>{r.title}</h3><p>{r.holder}</p><small>{r.subtitle}</small></div><i className={r.verified?'okdot':'pendingdot'}/><b>→</b></button>)}</div><Detail item={selected} edit={edit}/></section>}
function Detail({item,edit}:{item:RecordItem;edit:(r:RecordItem)=>void}){return <aside className="detail v2detail"><p className="eyebrow">FICHA DE COMPETENCIA</p><span className={`verifybadge ${item.verified?'yes':'wait'}`}>{item.verified?'✓ Verificado':'◷ Por confirmar'}</span><h2>{item.title}</h2><div className="person"><span>{item.holder.split(' ').map(x=>x[0]).slice(0,2).join('')}</span><div><b>{item.holder}</b><small>{item.subtitle}</small></div></div><section><p className="label">COMPETENCIA CENTRAL</p><p>{item.mission}</p></section><section className="legal"><p className="label">NORMA FUENTE</p><b>§ {item.norm}</b></section><section><p className="label">FUENTE</p><p>{item.source}</p><small>Revisión: {item.updated}</small></section><button className="primary" onClick={()=>edit(item)}>Proponer actualización ✎</button></aside>}
function Agenda(){return <section className="agenda"><div className="agendaHero"><p className="eyebrow">PROPUESTAS LEGISLATIVAS</p><h1>Del anuncio<br/>al Congreso.</h1><p>Solo incluimos iniciativas con una fuente oficial identificable. Diferenciamos proyectos vigentes, cerrados y aquellos cuyo estado requiere confirmación.</p><div className="agendaRules"><span>✓ Número o identificación</span><span>✓ Estado visible</span><span>✓ Enlace oficial</span></div></div><div className="billFeed"><div className="billHead"><h2>Radar legislativo</h2><span>{bills.length} fichas · corte 24 ago 2026</span></div>{bills.map((b,i)=><article className="bill" key={b.id}><span className="billnum">0{i+1}</span><div><div className="billmeta"><span>{b.kind}</span><time>{b.date}</time></div><p className="billid">{b.number}</p><h3>{b.title}</h3><p>{b.summary}</p><details><summary>Nota editorial</summary><p>{b.note}</p></details><a href={b.source} target="_blank">Consultar fuente oficial ↗</a></div><aside><span className={`billstatus ${b.status.includes('Archivado')?'closed':b.status.includes('confirmar')?'review':''}`}>{b.status}</span><small>Sector responsable</small><b>{b.sector}</b></aside></article>)}</div></section>}
function Editorial({drafts,edit,exportDrafts}:{drafts:Draft[];edit:(r:RecordItem)=>void;exportDrafts:()=>void}){const pending=allRecords.filter(r=>!r.verified);return <section className="editorial"><div className="editorhero"><p className="eyebrow">MECANISMO DE ACTUALIZACIÓN</p><h1>Mesa editorial</h1><p>Detectar → documentar → verificar → publicar.</p></div><div className="editorgrid"><section><div className="sectiontitle"><h2>Borradores en este dispositivo</h2><button disabled={!drafts.length} onClick={exportDrafts}>Exportar JSON ↓</button></div><p className="privacy">No cambian el sitio publicado hasta superar revisión por pares.</p>{drafts.length?drafts.map(d=>{const r=allRecords.find(x=>x.id===d.id)!;return <article className="draft" key={d.id}><span>PROPUESTA</span><h3>{r.title}</h3><p><s>{r.holder}</s> → <b>{d.holder}</b></p><small>{d.note}</small></article>}):<div className="empty">Aún no hay propuestas.</div>}</section><aside><h2>Cola de verificación</h2><b className="bigcount">{pending.length}</b>{pending.slice(0,6).map(r=><button key={r.id} onClick={()=>edit(r)}><span>{r.title}</span><small>{r.holder}</small></button>)}</aside></div></section>}
function EditModal({item,close,save}:{item:RecordItem;close:()=>void;save:(d:Draft)=>void}){const[holder,setHolder]=useState(item.holder);const[source,setSource]=useState(item.source);const[note,setNote]=useState('');return <div className="modalback"><form className="modal" onSubmit={e=>{e.preventDefault();save({id:item.id,holder,source,note,date:new Date().toISOString()})}}><button type="button" className="close" onClick={close}>×</button><p className="eyebrow">PROPUESTA EDITORIAL</p><h2>{item.title}</h2><label>Responsable<input required value={holder} onChange={e=>setHolder(e.target.value)}/></label><label>Fuente<input required value={source} onChange={e=>setSource(e.target.value)}/></label><label>Nota<textarea required value={note} onChange={e=>setNote(e.target.value)}/></label><div><button type="button" onClick={close}>Cancelar</button><button className="primary">Guardar borrador</button></div></form></div>}
